sudo: false

language: node_js

node_js:
  - node

services:
  - postgresql

env:
 global:
    - export NODE_ENV=stage
    - export AUTOMAILER_PASS=GmailGmail101!
    - export SECRET_KEY=abcd1234
    - export CLOUD_NAME=torsami77
    - export API_ID=242258518247965
    - export API_SECRET=2_AhysG0FjXvucPpytUs7lyHG-M
    - export CLOUDINARY_URL=cloudinary://242258518247965:2_AhysG0FjXvucPpytUs7lyHG-M@torsami77


cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g standard

before_script:
  - psql -c 'CREATE DATABASE testing_db;' -U postgres
  - psql -c 'CREATE TABLE users (id serial NOT NULL, email character varying NOT NULL, username character varying NOT NULL, first_name character varying NOT NULL, last_name character varying NOT NULL, password character varying NOT NULL, created_on date NOT NULL, address character varying NOT NULL, is_admin boolean);' -U postgres


after_success:
- nyc npm test
- nyc npm test && nyc report --reporter=text-lcov | coveralls

script:
  - npm test
