sudo: false

language: node_js

node_js:
  - node

services:
  - postgresql

env:
 global:
    - export NODE_ENV=stage
    - export AUTOMAILER_PASS=GmailGmail101!
    - export SECRET_KEY=abcd1234
    - export CLOUD_NAME=torsami77
    - export API_ID=242258518247965
    - export API_SECRET=2_AhysG0FjXvucPpytUs7lyHG-M
    - export CLOUDINARY_URL=cloudinary://242258518247965:2_AhysG0FjXvucPpytUs7lyHG-M@torsami77


cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g standard

after_success:
- nyc npm test
- nyc npm test && nyc report --reporter=text-lcov | coveralls

script:
  - npm test
