sudo: false

language: node_js

node_js:
  - node

env:
 global:
    - export NODE_ENV=stage
    - export CLOUD_NAME=torsami77
    - export API_ID=242258518247965
    - export API_SECRET=2_AhysG0FjXvucPpytUs7lyHG-M
    - export CLOUDINARY_URL=cloudinary://242258518247965:2_AhysG0FjXvucPpytUs7lyHG-M@torsami77
    - export AUTOMAILER_PASS=GmailGmail101!
    - export PG_STAGE_USER = rtogjrzarxrkze
    - export PG_STAGE_PASSWORD = 115cdc5315e36082dbfce54220f5d318b56c889d0821906a462ababcce645e28
    - export PG_STAGE_DATABASE = dd6bbaicuvbfvb
    - export PG_STAGE_HOST = ec2-174-129-240-67.compute-1.amazonaws.com
    - export PG_STAGE_PORT = 5432

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g standard

after_success:
- nyc npm test
- nyc npm test && nyc report --reporter=text-lcov | coveralls

script:
  - npm test
